version: '3'

services:
  gobarber-app:
    build:
      context: .
    container_name: app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    #ports:
    #  - "3000:3000"
    depends_on:
      - database
    networks:
      - node-network

  database:
    image: postgres
    container_name: gobarber-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_gobarber
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:6
    container_name: gobarber-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - node-network

  # mongodb:
  #   image: mongo
  #   container_name: gobarber-mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongo
  #     MONGO_INITDB_ROOT_PASSWORD: ''
  #   networks:
  #     - node-network

volumes:
  pgdata:
    driver: local
